# Generated by Django 5.2.18 on 2026-10-09 03:43

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('question_banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=apps.files.models.ruta_adjunto)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='exams.examen')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='question_banks.pregunta')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archivos_adjuntos',
                'ordering': ['-fecha_creacion', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('examen__isnull', True), ('pregunta__isnull', False)), models.Q(('examen__isnull', False), ('pregunta__isnull', True)), _connector='OR'), name='ck_adjunto_un_solo_dueno')],
            },
        ),
    ]
