# Generated by Django 5.2.18 on 2026-10-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('examen_asignado', 'Examen asignado'), ('examen_publicado', 'Examen publicado'), ('resultado_revisado', 'Resultado revisado')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=500)),
                ('entidad', models.CharField(blank=True, max_length=50)),
                ('entidad_id', models.CharField(blank=True, max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx')],
            },
        ),
    ]
