# Generated by Django 5.2.18 on 2026-10-07 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('entidad_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx'), models.Index(fields=['usuario', 'fecha'], name='auditoria_usuario_c2e4c1_idx'), models.Index(fields=['accion'], name='auditoria_accion_f32e20_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('entidad_id', models.CharField(max_length=50)),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_cambios',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='historial_c_entidad_c6230e_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('entidad_id', models.CharField(max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_estado',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='historial_e_entidad_f56dfe_idx')],
            },
        ),
    ]
