# Generated by Django 5.2.18 on 2026-10-07 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('intentos_permitidos', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='question_banks.materia')),
            ],
            options={
                'db_table': 'examenes',
            },
        ),
        migrations.CreateModel(
            name='AsignacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=12)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='exams.examen')),
            ],
            options={
                'db_table': 'asignaciones_examen',
            },
        ),
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('puntaje', models.FloatField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.examen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_examenes', to='question_banks.pregunta')),
            ],
            options={
                'db_table': 'examen_preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='examen',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='ck_examen_fechas'),
        ),
        migrations.AddConstraint(
            model_name='asignacionexamen',
            constraint=models.UniqueConstraint(fields=('examen', 'estudiante'), name='uq_asignacion_examen_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='examenpregunta',
            constraint=models.UniqueConstraint(fields=('examen', 'pregunta'), name='uq_examen_pregunta'),
        ),
    ]
