# Generated by Django 5.2.18 on 2026-10-07 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('question_banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_limite', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('finalizado', 'Finalizado'), ('expirado', 'Expirado'), ('anulado', 'Anulado')], default='en_progreso', max_length=12)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='exams.asignacionexamen')),
            ],
            options={
                'db_table': 'intentos',
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True)),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('es_correcta', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='attempts.intento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='question_banks.pregunta')),
            ],
            options={
                'db_table': 'respuestas_intento',
            },
        ),
        migrations.CreateModel(
            name='RespuestaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='question_banks.opcionrespuesta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleccion', to='attempts.respuestaintento')),
            ],
            options={
                'db_table': 'respuesta_opciones',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.FloatField(default=0)),
                ('puntaje_maximo', models.FloatField(default=0)),
                ('nota_final', models.FloatField(default=0)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('revisado', 'Revisado')], default='pendiente', max_length=12)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='attempts.intento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resultados_examen',
            },
        ),
        migrations.AddConstraint(
            model_name='intento',
            constraint=models.UniqueConstraint(fields=('asignacion', 'numero_intento'), name='uq_intento_asignacion_numero'),
        ),
        migrations.AddConstraint(
            model_name='intento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'en_progreso')), fields=('asignacion',), name='uq_intento_en_progreso'),
        ),
        migrations.AddConstraint(
            model_name='respuestaintento',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='uq_respuesta_intento_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='respuestaopcion',
            constraint=models.UniqueConstraint(fields=('respuesta', 'opcion'), name='uq_respuesta_opcion'),
        ),
    ]
