# Generated by Django 5.2.18 on 2026-10-09 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida_pestana', 'Salió de la pestaña'), ('pegado', 'Pegó texto')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='attempts.intento')),
            ],
            options={
                'db_table': 'eventos_intento',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
